// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKRE99TGxVIOYjDvCdUK_K0HbxRlGo-g',
    appId: '1:330401632420:web:6a6a6df3b3685b2f6c5631',
    messagingSenderId: '330401632420',
    projectId: 'fytbyte',
    authDomain: 'fytbyte.firebaseapp.com',
    storageBucket: 'fytbyte.firebasestorage.app',
    measurementId: 'G-QWERB8MSFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinyyQjtS0lsw25T0hXDDlqsIZ3dkp0Ho',
    appId: '1:330401632420:android:a8f566e8b76b2e646c5631',
    messagingSenderId: '330401632420',
    projectId: 'fytbyte',
    storageBucket: 'fytbyte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLo7xqALkNPB6XwQjcs0TKehCapbTtCc',
    appId: '1:330401632420:ios:363f257bc8ad78f36c5631',
    messagingSenderId: '330401632420',
    projectId: 'fytbyte',
    storageBucket: 'fytbyte.firebasestorage.app',
    iosBundleId: 'com.techiguru.fitByte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPLo7xqALkNPB6XwQjcs0TKehCapbTtCc',
    appId: '1:330401632420:ios:363f257bc8ad78f36c5631',
    messagingSenderId: '330401632420',
    projectId: 'fytbyte',
    storageBucket: 'fytbyte.firebasestorage.app',
    iosBundleId: 'com.techiguru.fitByte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQKRE99TGxVIOYjDvCdUK_K0HbxRlGo-g',
    appId: '1:330401632420:web:d2ab944a4619738f6c5631',
    messagingSenderId: '330401632420',
    projectId: 'fytbyte',
    authDomain: 'fytbyte.firebaseapp.com',
    storageBucket: 'fytbyte.firebasestorage.app',
    measurementId: 'G-5K10H708GX',
  );
}
